name: Build

# The workflow will start manually
on:
  workflow_dispatch:
  push:
    branches:
      - master


# Multiple jobs run in parallel
jobs:
  android_Build:
    name: Android App Building
    runs-on: ubuntu-20.04

    steps:
      # Checkouts the current branch for processing
      - name: Checkout
        uses: actions/checkout@v2

      # Setup the Java environment
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # Cache and restore the Gradle dependencies on multiple runs
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # Run android assembleProdDebuggable
      - name: Run Build
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1
          
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "app/"
          type: ".apk"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
          
      # Uploads the folder or file in path to GitHub
      - name: Upload Apk
        uses: actions/upload-artifact@v2
        with:
          name: DebugApp
          path: $i #app/build/outputs/apk/debug/
